version: '3.3'
services:
 db:
   container_name: postgres
   image: postgres
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: "12345"
   ports:
    - "5432:5432"
   volumes:
     - pgdata:/var/lib/postgresql/data/
 web:
  build: .
  command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/usr/src/app
  ports:
   - "8000:8000"
  depends_on:
  - db
  links:
  - db:db
volumes:
  pgdata:



#version: '3'
#volumes:
# dbdata:
#services:
#  app:
#    build: .
#    volumes :
#      - dbdata:/var/lib/mysql
#    networks:
#    - main  # Add the container to the network "main"
#    depends_on:
#    - db
#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_DATABASE: djangodocker_db
#      MYSQL_ROOT_PASSWORD: root
#      ports:
#        — "3306:3306"
#
#networks:
#  main:
#
#
#
