# Generated by Django 2.1.5 on 2019-01-24 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20181204_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 9, 27, 47, 344950, tzinfo=utc)),
        ),
    ]
